// Client-side report generator (Markdown + HTML export + browser print for PDF).

export function buildMarkdown(input) {
  const parts = [`# ${input.title}`];
  if (input.subtitle) parts.push(`> ${input.subtitle}`);
  parts.push("");
  for (const s of input.sections) {
    parts.push(`## ${s.title}`);
    parts.push("");
    parts.push(s.body);
    parts.push("");
  }
  parts.push("");
  parts.push(`_Generated by RepoDNA AI · ${new Date().toISOString()}_`);
  return parts.join("\n");
}
export function buildHtml(input) {
  const md = buildMarkdown(input);
  const html = md.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/^# (.+)$/gm, "<h1>$1</h1>").replace(/^## (.+)$/gm, "<h2>$1</h2>").replace(/^### (.+)$/gm, "<h3>$1</h3>").replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>").replace(/```([\s\S]*?)```/g, "<pre><code>$1</code></pre>").replace(/`([^`]+)`/g, "<code>$1</code>").replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>").replace(/^\- (.+)$/gm, "<li>$1</li>").replace(/(<li>[\s\S]*?<\/li>)/g, "<ul>$1</ul>").replace(/\n{2,}/g, "</p><p>").replace(/\n/g, "<br/>");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<title>${input.title}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Inter", system-ui, sans-serif; background:#F5F1E8; color:#1C1C1C; max-width: 900px; margin: 40px auto; padding: 0 24px 60px; line-height: 1.65; }
  h1 { font-family: "Fraunces", Georgia, serif; font-size: 40px; margin: 0 0 8px; letter-spacing: -0.02em; }
  h2 { font-family: "Fraunces", Georgia, serif; font-size: 26px; margin: 32px 0 8px; letter-spacing: -0.01em; border-bottom: 1px solid #d9d2be; padding-bottom: 6px; }
  h3 { font-size: 18px; margin: 20px 0 6px; }
  blockquote { border-left: 3px solid #6B7A3D; padding: 4px 12px; color: #4a4a4a; background:#efe9d6; }
  code { background:#efe9d6; padding: 1px 6px; border-radius: 4px; font-family: "JetBrains Mono", monospace; font-size: 12.5px; }
  pre { background:#1C1C1C; color:#F5F1E8; padding: 14px 16px; border-radius: 10px; overflow-x: auto; font-family: "JetBrains Mono", monospace; font-size: 12.5px; line-height: 1.55; }
  pre code { background: none; color: inherit; padding: 0; }
  ul { padding-left: 22px; }
  p { margin: 8px 0; }
  @media print { body { background: white; } pre { background: #f4f4f4; color: black; } }
</style></head><body><p>${html}</p></body></html>`;
}
export function downloadBlob(filename, content, mime) {
  const blob = new Blob([content], {
    type: mime
  });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 3000);
}
export function exportMarkdown(input, name) {
  downloadBlob(`${name}.md`, buildMarkdown(input), "text/markdown");
}
export function exportHtml(input, name) {
  downloadBlob(`${name}.html`, buildHtml(input), "text/html");
}
export function exportPdf(input) {
  const html = buildHtml(input);
  const win = window.open("", "_blank", "width=1000,height=800");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 400);
}