import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { toast } from "sonner";
import { RefreshCw, Loader2, Sparkles, Download, FileDown, TrendingUp, TrendingDown } from "lucide-react";
import Gauge from "@/components/features/Gauge";
import { aiHealth } from "@/lib/api";
import { parseId, fetchRepo } from "@/lib/github";
import { useAsync } from "@/hooks/useAsync";
import { exportMarkdown, exportPdf } from "@/lib/report";
import { db } from "@/lib/db";
import { cn } from "@/lib/utils";
const SUB_LABELS = {
  architecture: "Architecture",
  security: "Security",
  documentation: "Documentation",
  maintainability: "Maintainability",
  performance: "Performance",
  testing: "Testing",
  code_quality: "Code Quality",
  scalability: "Scalability",
  technical_debt: "Technical Debt"
};
export default function HealthScore() {
  const {
    id = ""
  } = useParams();
  const {
    owner,
    name
  } = parseId(id);
  const repoQ = useAsync(() => fetchRepo(owner, name), [owner, name]);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [initial, setInitial] = useState(true);
  useEffect(() => {
    (async () => {
      const {
        data
      } = await db.from("repo_health").select("*").eq("repo_id", id).maybeSingle();
      if (data) setReport(data);
      setInitial(false);
    })();
  }, [id]);
  const run = async (force = false) => {
    setLoading(true);
    try {
      const r = await aiHealth(id, force);
      setReport(r);
      toast.success("Health score generated");
    } catch (e) {
      toast.error("Health scoring failed", {
        description: e.message
      });
    } finally {
      setLoading(false);
    }
  };
  const exportReport = kind => {
    if (!report) return;
    const sections = [{
      title: "Overall Health",
      body: `**${report.overall} / 100**`
    }, {
      title: "Sub-scores",
      body: Object.entries(report.scores).map(([k, v]) => `- **${SUB_LABELS[k] ?? k}**: ${v}/100`).join("\n")
    }, {
      title: "Strengths",
      body: report.strengths.map(s => `- ${s}`).join("\n") || "_None identified._"
    }, {
      title: "Weaknesses",
      body: report.weaknesses.map(s => `- ${s}`).join("\n") || "_None identified._"
    }, {
      title: "Recommendations",
      body: report.recommendations.map(r => `- **[${r.priority.toUpperCase()}] ${r.title}** — ${r.action}`).join("\n")
    }];
    const input = {
      title: `Repository Health Report — ${repoQ.data?.full_name ?? id}`,
      subtitle: "Generated by RepoDNA AI",
      sections
    };
    if (kind === "md") exportMarkdown(input, `${owner}-${name}-health`);else exportPdf(input);
  };
  return <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <div className="font-mono text-[10px] uppercase tracking-[0.28em] text-olive">Repository intelligence</div>
          <h1 className="mt-2 font-serif text-3xl font-semibold tracking-tight">
            Health Score · {repoQ.data?.full_name ?? id}
          </h1>
          <p className="text-sm text-muted-foreground">
            Nine-dimension AI evaluation with prioritized recommendations.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button className="btn-ghost !py-2 !px-3" onClick={() => run(true)} disabled={loading}>
            <RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} /> Re-analyze
          </button>
          {report && <>
              <button className="btn-ghost !py-2 !px-3" onClick={() => exportReport("md")}>
                <Download className="h-4 w-4" /> Markdown
              </button>
              <button className="btn-primary !py-2 !px-3" onClick={() => exportReport("pdf")}>
                <FileDown className="h-4 w-4" /> PDF Report
              </button>
            </>}
        </div>
      </div>

      {initial ? <div className="glass h-72 animate-pulse rounded-2xl" /> : !report ? <div className="glass flex flex-col items-center rounded-3xl p-12 text-center">
          <div className="flex h-14 w-14 items-center justify-center rounded-full bg-gold/20 text-charcoal">
            <Sparkles className="h-6 w-6" />
          </div>
          <h3 className="mt-4 font-serif text-2xl font-semibold tracking-tight">Score this repository</h3>
          <p className="mt-2 max-w-md text-sm text-muted-foreground">
            Generate a nine-dimension health analysis with strengths, weaknesses, and prioritized recommendations.
          </p>
          <button className="btn-primary mt-6" onClick={() => run(false)} disabled={loading}>
            {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
            {loading ? "Analyzing…" : "Generate health score"}
          </button>
        </div> : <>
          <div className="glass grid gap-6 rounded-3xl p-8 md:grid-cols-[280px_1fr]">
            <Gauge value={report.overall} label="Overall Health" sublabel="Aggregate score" size={220} large />
            <div>
              <h3 className="font-serif text-2xl font-semibold tracking-tight">Executive assessment</h3>
              <div className="mt-3 grid gap-2">
                {report.strengths.length > 0 && <div className="rounded-xl border border-olive/30 bg-olive/5 p-3">
                    <div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-olive-dark">
                      <TrendingUp className="h-3.5 w-3.5" /> Top strengths
                    </div>
                    <ul className="mt-2 space-y-1 text-sm">
                      {report.strengths.slice(0, 4).map((s, i) => <li key={i}>• {s}</li>)}
                    </ul>
                  </div>}
                {report.weaknesses.length > 0 && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3">
                    <div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-destructive">
                      <TrendingDown className="h-3.5 w-3.5" /> Key weaknesses
                    </div>
                    <ul className="mt-2 space-y-1 text-sm">
                      {report.weaknesses.slice(0, 4).map((s, i) => <li key={i}>• {s}</li>)}
                    </ul>
                  </div>}
              </div>
            </div>
          </div>

          <div className="glass rounded-2xl p-6">
            <h3 className="font-serif text-xl font-semibold tracking-tight">Nine-dimension breakdown</h3>
            <div className="mt-6 grid grid-cols-2 gap-6 sm:grid-cols-3 lg:grid-cols-5">
              {Object.entries(report.scores).map(([k, v]) => <Gauge key={k} value={Number(v) || 0} label={SUB_LABELS[k] ?? k} size={120} />)}
            </div>
          </div>

          {report.recommendations.length > 0 && <div className="glass rounded-2xl p-6">
              <h3 className="font-serif text-xl font-semibold tracking-tight">Prioritized recommendations</h3>
              <ul className="mt-4 space-y-3">
                {report.recommendations.map((r, i) => <li key={i} className="rounded-xl border border-border/70 bg-cream-deep/40 p-4">
                    <div className="flex items-center gap-2">
                      <span className={cn("rounded-full px-2 py-0.5 font-mono text-[10px] uppercase tracking-widest", r.priority === "high" ? "bg-destructive/10 text-destructive" : r.priority === "medium" ? "bg-gold/20 text-charcoal" : "bg-cream text-muted-foreground")}>{r.priority}</span>
                      <div className="font-semibold">{r.title}</div>
                    </div>
                    <p className="mt-1.5 text-sm text-foreground/80">{r.action}</p>
                  </li>)}
              </ul>
            </div>}
        </>}
    </div>;
}