import { useState } from "react";
import { useParams } from "react-router-dom";
import { Copy, CheckCheck, MessageSquareQuote, Sparkles, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { fetchRepo, parseId } from "@/lib/github";
import { useAsync } from "@/hooks/useAsync";
import { aiInterview } from "@/lib/api";
import { cn } from "@/lib/utils";
const diffStyle = {
  easy: "border-olive/40 bg-olive/10 text-olive-dark",
  medium: "border-gold/40 bg-gold/10 text-charcoal",
  hard: "border-destructive/40 bg-destructive/10 text-destructive"
};
export default function InterviewGenerator() {
  const {
    id = ""
  } = useParams();
  const {
    owner,
    name
  } = parseId(id);
  const repoQ = useAsync(() => fetchRepo(owner, name), [owner, name]);
  const [track, setTrack] = useState("Screening");
  const [copied, setCopied] = useState(false);
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(false);
  const generate = async t => {
    setTrack(t);
    setLoading(true);
    setQuestions([]);
    try {
      const res = await aiInterview(id, t);
      setQuestions(res.questions ?? []);
      toast.success(`${t} kit generated`);
    } catch (e) {
      toast.error("Generation failed", {
        description: e.message
      });
    } finally {
      setLoading(false);
    }
  };
  const copyAll = () => {
    const md = `# ${track} interview · ${repoQ.data?.full_name ?? ""}\n\n${questions.map((q, i) => `${i + 1}. **${q.q}**\n   - _Topic:_ ${q.topic} · _Difficulty:_ ${q.difficulty}\n   - _Look for:_ ${q.look_for}`).join("\n\n")}`;
    navigator.clipboard.writeText(md);
    setCopied(true);
    toast.success("Interview kit copied");
    setTimeout(() => setCopied(false), 1500);
  };
  return <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <div className="font-mono text-[10px] uppercase tracking-[0.28em] text-olive">AI interview generator</div>
          <h1 className="mt-2 font-serif text-3xl font-semibold tracking-tight">
            Interview kit · {repoQ.data?.full_name ?? `${owner}/${name}`}
          </h1>
          <p className="text-sm text-muted-foreground">
            Repository-aware questions with rubrics, generated by Gemini.
          </p>
        </div>
        {questions.length > 0 && <button className="btn-ghost !py-2 !px-4" onClick={copyAll}>
            {copied ? <CheckCheck className="h-4 w-4 text-olive" /> : <Copy className="h-4 w-4" />}
            Copy kit
          </button>}
      </div>

      <div className="glass flex flex-wrap items-center gap-2 rounded-2xl p-2">
        {["Screening", "Junior", "Senior", "Architect"].map(t => <button key={t} onClick={() => generate(t)} disabled={loading} className={cn("rounded-full px-4 py-2 text-sm transition", track === t ? "bg-charcoal text-cream" : "hover:bg-cream-deep", loading && track !== t && "opacity-40")}>
            {t}
          </button>)}
        <div className="ml-auto flex items-center gap-2 rounded-full border border-olive/40 bg-olive/10 px-3 py-1.5 font-mono text-[11px] text-olive-dark">
          <Sparkles className="h-3.5 w-3.5" /> {loading ? "Generating…" : questions.length ? `${questions.length} questions` : "Select a track"}
        </div>
      </div>

      {loading ? <div className="glass flex items-center gap-3 rounded-2xl p-6 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin text-olive" /> Reading the repository and drafting questions…
        </div> : questions.length === 0 ? <div className="glass flex flex-col items-center rounded-3xl p-12 text-center">
          <MessageSquareQuote className="h-8 w-8 text-olive" />
          <h3 className="mt-3 font-serif text-2xl">Generate a repository-aware interview</h3>
          <p className="mt-2 max-w-md text-sm text-muted-foreground">
            Choose a track above to have Gemini produce grounded questions and a "what good looks like" rubric.
          </p>
        </div> : <ol className="space-y-3">
          {questions.map((q, i) => <li key={i} className="glass rounded-2xl p-5">
              <div className="flex items-start gap-3">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-olive/15 font-serif text-sm font-semibold text-olive-dark">
                  {i + 1}
                </span>
                <div className="min-w-0 flex-1">
                  <p className="font-serif text-lg font-semibold tracking-tight">{q.q}</p>
                  <div className="mt-2 flex flex-wrap gap-2 text-xs">
                    <span className={cn("rounded-full border px-2 py-0.5 font-mono uppercase tracking-widest", diffStyle[q.difficulty])}>
                      {q.difficulty}
                    </span>
                    <span className="badge-soft">{q.topic}</span>
                  </div>
                  <div className="mt-3 flex items-start gap-2 rounded-xl border border-gold/40 bg-gold/10 p-3 text-sm">
                    <MessageSquareQuote className="mt-0.5 h-4 w-4 shrink-0 text-charcoal" />
                    <div>
                      <span className="font-mono text-[10px] uppercase tracking-widest text-charcoal">Look for</span>
                      <p className="mt-1 text-sm text-foreground/80">{q.look_for}</p>
                    </div>
                  </div>
                </div>
              </div>
            </li>)}
        </ol>}
    </div>;
}